### ISSUE TITLE
ビデオ通話画面のPC版を開いた際に全画面表示になるようにする

### ISSUE THREAD

**Issue by near108** [near108/Remedy#36]
Javascriptで画面サイズを取得して、スマホサイズでなければ、全画面表示にする。
ページを閉じたときには、全画面表示を解除する。

**Comment by ffumiya** [comment]
全画面表示はクリックなどのイベントが行われないとできない仕様らしいです。
そのため、開いた瞬間に全画面になる代わりに全画面ボタンを押した時に、
スマホでなければ全画面に、スマホ画面ならエラ〜メッセージを表示するように実装しました。
